// Re-rates the whole bank and writes docs/difficulty-calibration.md: the
// evidence that the six tiers are really separated. Run: npm run calibrate
import { writeFileSync } from "node:fs";
import { BANK } from "../lib/sudoku/bank";
import { DIFFICULTIES, DIFFICULTY_CONFIG, type Difficulty } from "../lib/sudoku/engine";
import { ratePuzzle, TECHNIQUES, type Rating, type TechniqueId } from "../lib/sudoku/solver";

const median = (xs: number[]) => {
  const s = [...xs].sort((a, b) => a - b);
  return s.length ? s[Math.floor(s.length / 2)] : 0;
};
const mmss = (ms: number) => `${Math.floor(ms / 60000)}:${String(Math.round((ms % 60000) / 1000)).padStart(2, "0")}`;

const rows: Record<Difficulty, Rating[]> = { beginner: [], easy: [], medium: [], hard: [], expert: [], master: [] };
for (const tier of DIFFICULTIES) for (const [p] of BANK[tier]) rows[tier].push(ratePuzzle(p)!);

const lines: string[] = [];
lines.push("# Difficulty calibration", "", "Generated by `npm run calibrate`. Every puzzle in the bank is re-rated with the cheapest-first technique solver.", "");
lines.push("| Tier | Puzzles | DR min / median / max | Clues (median) | Steps (median) | Workload (median) | Par time (median) | Stalls (median) | Openness (median) |");
lines.push("|---|---|---|---|---|---|---|---|---|");
for (const t of DIFFICULTIES) {
  const r = rows[t];
  const f = (g: (x: Rating) => number) => median(r.map(g));
  lines.push(
    `| ${DIFFICULTY_CONFIG[t].label} | ${r.length} | ${Math.min(...r.map((x) => x.dr)).toFixed(2)} / ${f((x) => x.dr).toFixed(2)} / ${Math.max(...r.map((x) => x.dr)).toFixed(2)} | ${81 - f((x) => x.empties)} | ${f((x) => x.steps)} | ${f((x) => x.workload)} | ${mmss(f((x) => x.parMs))} | ${f((x) => x.stalls)} | ${f((x) => x.openness)} |`,
  );
}
lines.push("", "## Separation between adjacent tiers", "", "| From → To | Median workload ratio | Median par-time ratio | DR bands overlap? |", "|---|---|---|---|");
let ok = true;
for (let i = 1; i < DIFFICULTIES.length; i++) {
  const [a, b] = [rows[DIFFICULTIES[i - 1]], rows[DIFFICULTIES[i]]];
  const wr = median(b.map((x) => x.workload)) / Math.max(1, median(a.map((x) => x.workload)));
  const pr = median(b.map((x) => x.parMs)) / Math.max(1, median(a.map((x) => x.parMs)));
  const overlap = Math.max(...a.map((x) => x.dr)) >= Math.min(...b.map((x) => x.dr));
  if (overlap) ok = false;
  lines.push(`| ${DIFFICULTY_CONFIG[DIFFICULTIES[i - 1]].label} → ${DIFFICULTY_CONFIG[DIFFICULTIES[i]].label} | ×${wr.toFixed(2)} | ×${pr.toFixed(2)} | ${overlap ? "YES" : "no"} |`);
}
lines.push("", `Bands disjoint: **${ok ? "yes" : "NO"}**.`, "", "## Hardest technique required, by tier", "");
lines.push("| Tier | Hardest technique (share of puzzles) |", "|---|---|");
for (const t of DIFFICULTIES) {
  const c: Partial<Record<TechniqueId, number>> = {};
  for (const x of rows[t]) c[x.hardest] = (c[x.hardest] ?? 0) + 1;
  const cell = Object.entries(c)
    .sort((a, b) => b[1] - a[1])
    .map(([id, n]) => `${TECHNIQUES[id as TechniqueId].name} ${Math.round((n / rows[t].length) * 100)}%`)
    .join(", ");
  lines.push(`| ${DIFFICULTY_CONFIG[t].label} | ${cell} |`);
}
writeFileSync("docs/difficulty-calibration.md", lines.join("\n") + "\n");
console.log(lines.join("\n"));
